# Dependencies
markdown:         kramdown
rouge:            pygments

# Permalinks
permalink:        pretty

# Setup
title:            'L. Roser site'
tagline:          
description:      ''
url:              http://leandroroser.github.io
baseurl:          /

author:
  name:           'Leandro Roser'
  url:            

paginate:         5

# Custom vars

github:
  repo:           https://github.com/leandroroser
