# Dependencies
markdown:         kramdown
rouge:            pygments

# Permalinks
permalink:        pretty

# Setup
title:            '   #Hello World'
tagline:          
description:      'Lenguage games in <a href="http://jekyllrb.com" target="_blank">R flavors. </a>'
url:              http://leandroroser.github.io
baseurl:          /

author:
  name:           'Leandro Roser'
  url:            

paginate:         5

# Custom vars

github:
  repo:           https://github.com/leandroroser
