# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            '#Hello World'
tagline:          
description:      'Lenguage games in <a href="http://jekyllrb.com" target="_blank">R</a> flavors.'
url:              http://leandroroser.github.io
baseurl:          /

author:
  name:           'Leandro Roser'
  url:            

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/leandroroser
