# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            '#Hello World'
tagline:          
description:      'Lenguage games <a href="http://jekyllrb.com" target="_blank">in R flavors</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Leandro Roser'
  url:            

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/leandroroser
